import { describe, expect, it } from "@effect/vitest";
import { ProviderInstanceId } from "@t3tools/contracts";
import {
  buildModelHandoffMessage,
  buildTranscriptHandoffFallback,
  MODEL_HANDOFF_SUMMARY_REQUEST,
  MODEL_HANDOFF_WAIT_INSTRUCTION,
  modelHandoffActionId,
  parseModelHandoffActionId,
} from "./modelHandoff";

const source = {
  instanceId: ProviderInstanceId.make("codex"),
  model: "gpt-6-astra",
};
const target = {
  instanceId: ProviderInstanceId.make("claudeAgent"),
  model: "claude-opus-5",
};

describe("model handoff", () => {
  it("round-trips provider/model action ids including punctuation", () => {
    const selection = {
      instanceId: ProviderInstanceId.make("opencode_personal"),
      model: "openrouter/example:model:free",
    };

    expect(parseModelHandoffActionId(modelHandoffActionId(selection))).toEqual(selection);
    expect(parseModelHandoffActionId("rename")).toBeNull();
  });

  it("asks the source model to summarize without continuing the task", () => {
    expect(MODEL_HANDOFF_SUMMARY_REQUEST).toContain("Prepare a concise handoff summary");
    expect(MODEL_HANDOFF_SUMMARY_REQUEST).toContain("Do not continue the task");
    expect(MODEL_HANDOFF_SUMMARY_REQUEST).toContain("Return only the handoff summary");
  });

  it("builds the target-model catch-up message from the generated summary", () => {
    const message = buildModelHandoffMessage({
      threadTitle: "Fix provider switching",
      branch: "feat/provider-switch",
      sourceModelSelection: source,
      targetModelSelection: target,
      summary: [
        "The user wants safe provider switching without losing context.",
        "Initial routing changes are complete; tests still need to be finished.",
      ].join("\n"),
    });

    expect(message).toContain("## Summary generated by the previous model");
    expect(message).toContain("Source model: gpt-6-astra");
    expect(message).toContain("Target model: claude-opus-5");
    expect(message).toContain("branch feat/provider-switch");
    expect(message).toContain("Initial routing changes are complete");
    expect(message).toContain(MODEL_HANDOFF_WAIT_INSTRUCTION);
  });

  it("falls back to recent transcript context when the source model cannot summarize", () => {
    const fallback = buildTranscriptHandoffFallback([
      { role: "user", text: "Add a model handoff feature." },
      { role: "assistant", text: "The handoff workflow is implemented on feat/model-handoff." },
    ]);
    const message = buildModelHandoffMessage({
      threadTitle: "Model handoff",
      branch: "feat/model-handoff",
      sourceModelSelection: source,
      targetModelSelection: target,
      summary: fallback,
      summarySource: "transcript-fallback",
    });

    expect(fallback).toContain("USER: Add a model handoff feature.");
    expect(fallback).toContain("ASSISTANT: The handoff workflow is implemented");
    expect(message).toContain("## Recent transcript fallback");
    expect(message).toContain(MODEL_HANDOFF_WAIT_INSTRUCTION);
  });

  it("explicitly prevents the target model from acting until the next user message", () => {
    expect(MODEL_HANDOFF_WAIT_INSTRUCTION).toContain("Do not continue the task yet");
    expect(MODEL_HANDOFF_WAIT_INSTRUCTION).toContain("Do not inspect files");
    expect(MODEL_HANDOFF_WAIT_INSTRUCTION).toContain(
      "wait for the user's next message before taking any action",
    );
  });
});
