import type { ModelSelection } from "@t3tools/contracts";

export type ModelHandoffActionId = `handoff-model:${string}:${string}`;
export type ModelHandoffSummarySource = "source-model" | "transcript-fallback";

export interface ModelHandoffMessageInput {
  readonly threadTitle: string;
  readonly branch: string | null;
  readonly sourceModelSelection: ModelSelection;
  readonly targetModelSelection: ModelSelection;
  readonly summary: string;
  readonly summarySource?: ModelHandoffSummarySource;
}

export interface ModelHandoffTranscriptMessage {
  readonly role: string;
  readonly text: string;
}

export const MODEL_HANDOFF_SUMMARY_REQUEST = [
  "Prepare a concise handoff summary for another model that will continue this conversation later.",
  "Do not continue the task, use tools, inspect files, run commands, or modify anything for this request.",
  "Summarize only what the next model needs to know: the user's goal, important decisions and constraints, work already completed, relevant files or code areas, tests/status, unresolved problems, and the latest state of the task.",
  "Preserve concrete names, paths, commands, errors, and decisions when they matter.",
  "Return only the handoff summary. Do not add a preamble, offer to continue, or take any further action.",
].join("\n");

export const MODEL_HANDOFF_WAIT_INSTRUCTION = [
  "IMPORTANT HANDOFF INSTRUCTION:",
  "This message is only transferring context from the previous model. Do not continue the task yet.",
  "Do not inspect files, run tools or commands, modify code, make plans, or infer that the summary itself is a request to act.",
  "Reply only with: \"Caught up — waiting for your next message.\"",
  "After that, wait for the user's next message before taking any action.",
].join("\n");

const FALLBACK_MAX_MESSAGES = 16;
const FALLBACK_MAX_CHARS = 12_000;

function compactSummary(summary: string): string {
  return summary.trim();
}

export function buildTranscriptHandoffFallback(
  messages: ReadonlyArray<ModelHandoffTranscriptMessage>,
): string {
  const candidates = messages
    .filter((message) => message.text.trim().length > 0)
    .slice(-FALLBACK_MAX_MESSAGES)
    .map((message) => `${message.role.toUpperCase()}: ${message.text.trim()}`);

  if (candidates.length === 0) {
    return "No prior text messages were available. Use only the thread/workspace metadata above and wait for the user's next message.";
  }

  const joined = candidates.join("\n\n");
  if (joined.length <= FALLBACK_MAX_CHARS) {
    return [
      "The previous model could not generate a handoff summary. Use this recent transcript as catch-up context only:",
      "",
      joined,
    ].join("\n");
  }

  const tail = joined.slice(-FALLBACK_MAX_CHARS);
  return [
    "The previous model could not generate a handoff summary. Use this truncated recent transcript as catch-up context only:",
    "",
    `[Earlier transcript omitted]\n${tail}`,
  ].join("\n");
}

export function buildModelHandoffMessage(input: ModelHandoffMessageInput): string {
  const workspace = input.branch ? `branch ${input.branch}` : "the current project workspace";
  const summary = compactSummary(input.summary);
  const summaryHeading =
    input.summarySource === "transcript-fallback"
      ? "## Recent transcript fallback"
      : "## Summary generated by the previous model";

  return [
    "# Model handoff",
    "",
    `Source thread: ${input.threadTitle}`,
    `Source model: ${input.sourceModelSelection.model}`,
    `Target model: ${input.targetModelSelection.model}`,
    `Workspace: ${workspace}`,
    "",
    summaryHeading,
    summary,
    "",
    "---",
    MODEL_HANDOFF_WAIT_INSTRUCTION,
  ].join("\n");
}

export function modelHandoffActionId(selection: ModelSelection): ModelHandoffActionId {
  return `handoff-model:${encodeURIComponent(selection.instanceId)}:${encodeURIComponent(selection.model)}`;
}

export function parseModelHandoffActionId(action: string): ModelSelection | null {
  if (!action.startsWith("handoff-model:")) return null;
  const encoded = action.slice("handoff-model:".length);
  const separator = encoded.indexOf(":");
  if (separator <= 0 || separator === encoded.length - 1) return null;

  try {
    const instanceId = decodeURIComponent(encoded.slice(0, separator));
    const model = decodeURIComponent(encoded.slice(separator + 1));
    if (!instanceId || !model) return null;
    return { instanceId, model } as ModelSelection;
  } catch {
    return null;
  }
}
